-- BLACKOUT backend schema: usernames, device telemetry, leaderboards and realtime rooms.
-- Idempotent: safe to run from the Supabase SQL editor more than once.

create extension if not exists pgcrypto;

create table if not exists public.players (
  device_id uuid primary key,
  name text not null unique check (char_length(name) between 2 and 16),
  name_normalized text generated always as (lower(name)) stored unique,
  device_info jsonb not null default '{}'::jsonb,
  last_ip inet,
  last_port integer,
  last_country text,
  last_region text,
  last_city text,
  last_language text,
  last_user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.player_devices (
  id uuid primary key default gen_random_uuid(),
  player_device_id uuid not null references public.players(device_id) on delete cascade,
  device_info jsonb not null default '{}'::jsonb,
  ip inet,
  port integer,
  country text,
  region text,
  city text,
  user_agent text,
  seen_at timestamptz not null default now()
);

create table if not exists public.leaderboards (
  id uuid primary key default gen_random_uuid(),
  board text not null check (board in ('times', 'survival', 'credits')),
  player_device_id uuid references public.players(device_id) on delete set null,
  player_name text not null,
  score_value numeric not null,
  display_value text not null,
  meta jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now()
);
create index if not exists leaderboards_board_score_idx on public.leaderboards(board, score_value);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  max_players integer not null check (max_players between 2 and 4),
  host_device_id uuid references public.players(device_id) on delete set null,
  status text not null default 'waiting' check (status in ('waiting', 'countdown', 'playing', 'closed')),
  countdown_started_at timestamptz,
  game_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.room_players (
  room_id uuid not null references public.rooms(id) on delete cascade,
  session_id uuid not null,
  player_device_id uuid references public.players(device_id) on delete set null,
  player_name text not null,
  is_host boolean not null default false,
  ready boolean not null default false,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (room_id, session_id)
);

create table if not exists public.player_states (
  room_id uuid not null references public.rooms(id) on delete cascade,
  session_id uuid not null,
  x numeric not null default 0,
  y numeric not null default 0,
  orientation text not null default 'down' check (orientation in ('left', 'right', 'up', 'down')),
  walking boolean not null default false,
  hidden boolean not null default false,
  items jsonb not null default '[]'::jsonb,
  action jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (room_id, session_id)
);

create table if not exists public.room_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  actor_session_id uuid,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.players enable row level security;
alter table public.player_devices enable row level security;
alter table public.leaderboards enable row level security;
alter table public.rooms enable row level security;
alter table public.room_players enable row level security;
alter table public.player_states enable row level security;
alter table public.room_events enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.players to anon, authenticated;
grant insert on public.player_devices to anon, authenticated;
grant select, insert on public.leaderboards to anon, authenticated;
grant select, insert, update on public.rooms to anon, authenticated;
grant select, insert, update, delete on public.room_players to anon, authenticated;
grant select, insert, update, delete on public.player_states to anon, authenticated;
grant select, insert on public.room_events to anon, authenticated;
grant usage, select on sequence public.room_events_id_seq to anon, authenticated;

-- Client-safe player policies. The RPC below remains the canonical path, but
-- these policies keep PostgREST/FK-related reads and repairs from being blocked
-- by RLS when a browser session uses the anon publishable key.
drop policy if exists "public players read" on public.players;
create policy "public players read" on public.players for select using (true);
drop policy if exists "public players insert" on public.players;
create policy "public players insert" on public.players for insert with check (true);
drop policy if exists "public players update" on public.players;
create policy "public players update" on public.players for update using (true) with check (true);
drop policy if exists "public player devices insert" on public.player_devices;
create policy "public player devices insert" on public.player_devices for insert with check (true);

drop policy if exists "public leaderboard read" on public.leaderboards;
create policy "public leaderboard read" on public.leaderboards for select using (true);
drop policy if exists "public leaderboard insert" on public.leaderboards;
create policy "public leaderboard insert" on public.leaderboards for insert with check (true);
drop policy if exists "public rooms read" on public.rooms;
create policy "public rooms read" on public.rooms for select using (true);
drop policy if exists "public rooms insert" on public.rooms;
create policy "public rooms insert" on public.rooms for insert with check (true);
drop policy if exists "public rooms update" on public.rooms;
create policy "public rooms update" on public.rooms for update using (true) with check (true);
drop policy if exists "public room players read" on public.room_players;
create policy "public room players read" on public.room_players for select using (true);
drop policy if exists "public room players insert" on public.room_players;
create policy "public room players insert" on public.room_players for insert with check (true);
drop policy if exists "public room players update" on public.room_players;
create policy "public room players update" on public.room_players for update using (true) with check (true);
drop policy if exists "public room players delete" on public.room_players;
create policy "public room players delete" on public.room_players for delete using (true);
drop policy if exists "public states read" on public.player_states;
create policy "public states read" on public.player_states for select using (true);
drop policy if exists "public states upsert" on public.player_states;
create policy "public states upsert" on public.player_states for all using (true) with check (true);
drop policy if exists "public events read" on public.room_events;
create policy "public events read" on public.room_events for select using (true);
drop policy if exists "public events insert" on public.room_events;
create policy "public events insert" on public.room_events for insert with check (true);

create or replace function public.claim_player_name(p_name text, p_device_id uuid, p_device_info jsonb default '{}'::jsonb)
returns table(allowed boolean, reason text, device_id uuid, name text, created_at timestamptz, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  existing public.players%rowtype;
  headers jsonb := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  ip_text text := split_part(coalesce(headers->>'x-forwarded-for', headers->>'cf-connecting-ip', ''), ',', 1);
  port_text text := headers->>'x-forwarded-port';
begin
  p_name := btrim(p_name);
  if char_length(p_name) < 2 or char_length(p_name) > 16 then
    return query select false, 'el nombre debe tener entre 2 y 16 caracteres', p_device_id, p_name, null::timestamptz, null::timestamptz;
    return;
  end if;

  select * into existing from public.players where lower(players.name) = lower(p_name) limit 1;
  if found and existing.device_id <> p_device_id then
    return query select false, 'ese nombre ya está ligado a otro dispositivo', existing.device_id, existing.name, existing.created_at, existing.updated_at;
    return;
  end if;

  insert into public.players(device_id, name, device_info, last_ip, last_port, last_country, last_region, last_city, last_language, last_user_agent)
  values (p_device_id, p_name, p_device_info, nullif(ip_text, '')::inet, nullif(port_text, '')::integer,
          headers->>'cf-ipcountry', headers->>'x-vercel-ip-country-region', headers->>'x-vercel-ip-city',
          p_device_info->>'language', p_device_info->>'user_agent')
  on conflict (device_id) do update set
    name = excluded.name,
    device_info = excluded.device_info,
    last_ip = excluded.last_ip,
    last_port = excluded.last_port,
    last_country = excluded.last_country,
    last_region = excluded.last_region,
    last_city = excluded.last_city,
    last_language = excluded.last_language,
    last_user_agent = excluded.last_user_agent,
    updated_at = now(),
    last_seen_at = now();

  insert into public.player_devices(player_device_id, device_info, ip, port, country, region, city, user_agent)
  values (p_device_id, p_device_info, nullif(ip_text, '')::inet, nullif(port_text, '')::integer,
          headers->>'cf-ipcountry', headers->>'x-vercel-ip-country-region', headers->>'x-vercel-ip-city', p_device_info->>'user_agent');

  return query select true, null::text, p.device_id, p.name, p.created_at, p.updated_at from public.players p where p.device_id = p_device_id;
end;
$$;

grant execute on function public.claim_player_name(text, uuid, jsonb) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'rooms'
  ) then
    alter publication supabase_realtime add table public.rooms;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'room_players'
  ) then
    alter publication supabase_realtime add table public.room_players;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'player_states'
  ) then
    alter publication supabase_realtime add table public.player_states;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'room_events'
  ) then
    alter publication supabase_realtime add table public.room_events;
  end if;
end;
$$;

alter table public.rooms replica identity full;
alter table public.room_players replica identity full;
alter table public.player_states replica identity full;
alter table public.room_events replica identity full;

-- Verification: this returns every BLACKOUT object expected by the game.
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('players', 'player_devices', 'leaderboards', 'rooms', 'room_players', 'player_states', 'room_events')
order by table_name;

select routine_name
from information_schema.routines
where routine_schema = 'public'
  and routine_name = 'claim_player_name';
